#!/usr/bin/env python3
# -*- coding: UTF-8 -*-



from bge import events


ALPHABET_KEYS = {   events.AKEY: "A",
                    events.BKEY: "B",
                    events.CKEY: "C",
                    events.DKEY: "D",
                    events.EKEY: "E",
                    events.FKEY: "F",
                    events.GKEY: "G",
                    events.HKEY: "H",
                    events.IKEY: "I",
                    events.JKEY: "J",
                    events.KKEY: "K",
                    events.LKEY: "L",
                    events.MKEY: "M",
                    events.NKEY: "N",
                    events.OKEY: "O",
                    events.PKEY: "P",
                    events.QKEY: "Q",
                    events.RKEY: "R",
                    events.SKEY: "S",
                    events.TKEY: "T",
                    events.UKEY: "U",
                    events.VKEY: "V",
                    events.WKEY: "W",
                    events.XKEY: "X",
                    events.YKEY: "Y",
                    events.ZKEY: "Z"}

# #NUMBER_KEY = {  events.ZEROKEY: "0",
                # #events.ONEKEY: "1",
                # #events.TWOKEY: "2",
                # #events.THREEKEY: "3",
                # #events.FOURKEY: "4",
                # #events.FIVEKEY: "5",
                # #events.SIXKEY: "6",
                # #events.SEVENKEY: "7",
                # #events.EIGHTKEY: "8",
                # #events.NINEKEY: "9"}

# #CAPS_LOCK_KEYS = {  events.CAPSLOCK: "CAPSLOCK",
                    # #events.LEFTCTRL: "LEFTCTRL",
                    # #events.LEFTALT: "LEFTALT",
                    # #events.RIGHTALT: "RIGHTALT",
                    # #events.RIGHTCTRL: "RIGHTCTRL",
                    # #events.RIGHTSHIFT: "RIGHTSHIFT",
                    # #events.LEFTSHIFT: "LEFTSHIFT"}

# #ARROW_KEYS = {  events.LEFTARROWKEY:"LEFT",
                # #events.DOWNARROW: "DOWN",
                # #events.RIGHTARROW: "RIGHT",
                # #events.UPARROW: "UP"}

# #NUMBER_PAD_KEYS = { events.PAD0: "0",
                    # #events.PAD1: "1",
                    # #events.PAD2: "2",
                    # #events.PAD3: "3",
                    # #events.PAD4: "4",
                    # #events.PAD5: "5",
                    # #events.PAD6: "6",
                    # #events.PAD7: "7",
                    # #events.PAD8: "8",
                    # #events.PAD9: "9",
                    # #events.PADPERIOD: "PERIOD",
                    # #events.PADSLASHKEY: "SLASH",
                    # #events.PADASTERKEY: "ASTER",
                    # #events.PADMINUS: "MINUS",
                    # #events.PADENTER: "ENTER",
                    # #events.PADPLUSKEY: "PLUS"}

# #FUNCTION_KEYS = {   events.F1: "F1",
                    # #events.F2: "F2",
                    # #events.F3: "F3",
                    # #events.F4: "F4",
                    # #events.F5: "F5",
                    # #events.F6: "F6",
                    # #events.F7: "F7",
                    # #events.F8: "F8",
                    # #events.F9: "F9",
                    # #events.F10: "F10",
                    # #events.F11: "F11",
                    # #events.F12: "F12",
                    # #events.F13: "F13",
                    # #events.F14: "F14",
                    # #events.F15: "F15",
                    # #events.F16: "F16",
                    # #events.F17: "F17",
                    # #events.F18: "F18",
                    # #events.F19: "F19"}

# #OTHER_KEYS = {  events.ACCENTGRAVE: "ACCENTGRAVE",
                # #events.BACKSLASH: "BACKSLASH",
                # #events.BACKSPACE: "BACKSPACE",
                # #events.COMMA: "COMMA",
                # #events.DEL: "DEL",
                # #events.END: "END",
                # #events.EQUAL: "EQUAL",
                # #events.ESC: "ESC",
                # #events.HOME: "HOME",
                # #events.INSERT: "INSERT",
                # #events.LEFTBRACKET: "LEFTBRACKET",
                # #events.LINEFEED: "LINEFEED",
                # #events.MINUS: "MINUS",
                # #events.PAGEDOWN: "PAGEDOWN",
                # #events.PAGEUP: "PAGEUP",
                # #events.PAUSE: "PAUSE",
                # #events.PERIOD: "PERIOD",
                # #events.QUOTE: "QUOTE",
                # #events.RIGHTBRACKET: "RIGHTBRACKET",
                # #events.ENTER: "ENTER",
                # #events.SEMICOLON: "SEMICOLON",
                # #events.SLASH: "SLASH",
                # #events.SPACE: "SPACE",
                # #events.TAB: "TAB"}
