#!/usr/bin/env python3
# -*- coding: UTF-8 -*-



from bge import events


ALL_KEYS = {events.AKEY: "A",
            events.BKEY: "B",
            events.CKEY: "C",
            events.DKEY: "D",
            events.EKEY: "E",
            events.FKEY: "F",
            events.GKEY: "G",
            events.HKEY: "H",
            events.IKEY: "I",
            events.JKEY: "J",
            events.KKEY: "K",
            events.LKEY: "L",
            events.MKEY: "M",
            events.NKEY: "N",
            events.OKEY: "O",
            events.PKEY: "P",
            events.QKEY: "Q",
            events.RKEY: "R",
            events.SKEY: "S",
            events.TKEY: "T",
            events.UKEY: "U",
            events.VKEY: "V",
            events.WKEY: "W",
            events.XKEY: "X",
            events.YKEY: "Y",
            events.ZKEY: "Z",
            events.SPACEKEY: " "}
            
            # #events.ONEKEY: "1",
            # #events.TWOKEY: "2"}

"""
ALPHABET_KEYS = {   events.AKEY: "A",
                    events.BKEY: "B",
                    events.CKEY: "C",
                    events.DKEY: "D",
                    events.EKEY: "E",
                    events.FKEY: "F",
                    events.GKEY: "G",
                    events.HKEY: "H",
                    events.IKEY: "I",
                    events.JKEY: "J",
                    events.KKEY: "K",
                    events.LKEY: "L",
                    events.MKEY: "M",
                    events.NKEY: "N",
                    events.OKEY: "O",
                    events.PKEY: "P",
                    events.QKEY: "Q",
                    events.RKEY: "R",
                    events.SKEY: "S",
                    events.TKEY: "T",
                    events.UKEY: "U",
                    events.VKEY: "V",
                    events.WKEY: "W",
                    events.XKEY: "X",
                    events.YKEY: "Y",
                    events.ZKEY: "Z"}
                    
NUMBER_KEY = {  events.ZEROKEY: "0",
                events.ONEKEY: "1",
                events.TWOKEY: "2",
                events.THREEKEY: "3",
                events.FOURKEY: "4",
                events.FIVEKEY: "5",
                events.SIXKEY: "6",
                events.SEVENKEY: "7",
                events.EIGHTKEY: "8",
                events.NINEKEY: "9"}

CAPS_LOCK_KEYS = {  events.CAPSLOCK: "CAPSLOCK",
                    events.LEFTCTRL: "LEFTCTRL",
                    events.LEFTALT: "LEFTALT",
                    events.RIGHTALT: "RIGHTALT",
                    events.RIGHTCTRL: "RIGHTCTRL",
                    events.RIGHTSHIFT: "RIGHTSHIFT",
                    events.LEFTSHIFT: "LEFTSHIFT"}

ARROW_KEYS = {  events.LEFTARROWKEY:"LEFT",
                events.DOWNARROW: "DOWN",
                events.RIGHTARROW: "RIGHT",
                events.UPARROW: "UP"}

NUMBER_PAD_KEYS = { events.PAD0: "0",
                    events.PAD1: "1",
                    events.PAD2: "2",
                    events.PAD3: "3",
                    events.PAD4: "4",
                    events.PAD5: "5",
                    events.PAD6: "6",
                    events.PAD7: "7",
                    events.PAD8: "8",
                    events.PAD9: "9",
                    events.PADPERIOD: "PERIOD",
                    events.PADSLASHKEY: "SLASH",
                    events.PADASTERKEY: "ASTER",
                    events.PADMINUS: "MINUS",
                    events.PADENTER: "ENTER",
                    events.PADPLUSKEY: "PLUS"}

FUNCTION_KEYS = {   events.F1KEY: "F1",
                    events.F2KEY: "F2",
                    events.F3KEY: "F3",
                    events.F4KEY: "F4",
                    events.F5KEY: "F5",
                    events.F6KEY: "F6",
                    events.F7KEY: "F7",
                    events.F8KEY: "F8",
                    events.F9KEY: "F9",
                    events.F10KEY: "F10",
                    events.F11KEY: "F11",
                    events.F12KEY: "F12",
                    events.F13KEY: "F13",
                    events.F14KEY: "F14",
                    events.F15KEY: "F15",
                    events.F16KEY: "F16",
                    events.F17KEY: "F17",
                    events.F18KEY: "F18",
                    events.F19KEY: "F19"}

OTHER_KEYS = {  events.ACCENTGRAVEKEY: "ACCENTGRAVE",
                events.BACKSLASHKEY: "BACKSLASH",
                events.BACKSPACEKEY: "BACKSPACE",
                events.COMMAKEY: "COMMA",
                events.DELKEY: "DEL",
                events.ENDKEY: "END",
                events.EQUALKEY: "EQUAL",
                events.ESCKEY: "ESC",
                events.HOMEKEY: "HOME",
                events.INSERTKEY: "INSERT",
                events.LEFTBRACKETKEY: "LEFTBRACKET",
                events.LINEFEEDKEY: "LINEFEED",
                events.MINUSKEY: "MINUS",
                events.PAGEDOWNKEY: "PAGEDOWN",
                events.PAGEUPKEY: "PAGEUP",
                events.PAUSEKEY: "PAUSE",
                events.PERIODKEY: "PERIOD",
                events.QUOTEKEY: "QUOTE",
                events.RIGHTBRACKETKEY: "RIGHTBRACKET",
                events.ENTERKEY: "ENTER",
                events.SEMICOLONKEY: "SEMICOLON",
                events.SLASHKEYKEY: "SLASH",
                events.SPACEKEYKEY: "SPACE",
                events.TABKEYKEY: "TAB"}
"""
